//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.quakeml.xmlns.bed._1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for AmplitudeCategory</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="AmplitudeCategory">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="point"/>
 *     <enumeration value="mean"/>
 *     <enumeration value="duration"/>
 *     <enumeration value="period"/>
 *     <enumeration value="integral"/>
 *     <enumeration value="other"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "AmplitudeCategory")
@XmlEnum
public enum AmplitudeCategory {

    @XmlEnumValue("point")
    POINT("point"),
    @XmlEnumValue("mean")
    MEAN("mean"),
    @XmlEnumValue("duration")
    DURATION("duration"),
    @XmlEnumValue("period")
    PERIOD("period"),
    @XmlEnumValue("integral")
    INTEGRAL("integral"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    AmplitudeCategory(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static AmplitudeCategory fromValue(String v) {
        for (AmplitudeCategory c: AmplitudeCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
