//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.quakeml.xmlns.bed._1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for DataUsedWaveType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="DataUsedWaveType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="P waves"/>
 *     <enumeration value="body waves"/>
 *     <enumeration value="surface waves"/>
 *     <enumeration value="mantle waves"/>
 *     <enumeration value="combined"/>
 *     <enumeration value="unknown"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "DataUsedWaveType")
@XmlEnum
public enum DataUsedWaveType {

    @XmlEnumValue("P waves")
    P_WAVES("P waves"),
    @XmlEnumValue("body waves")
    BODY_WAVES("body waves"),
    @XmlEnumValue("surface waves")
    SURFACE_WAVES("surface waves"),
    @XmlEnumValue("mantle waves")
    MANTLE_WAVES("mantle waves"),
    @XmlEnumValue("combined")
    COMBINED("combined"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    DataUsedWaveType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static DataUsedWaveType fromValue(String v) {
        for (DataUsedWaveType c: DataUsedWaveType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
