//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.quakeml.xmlns.bed._1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for EventDescriptionType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="EventDescriptionType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="felt report"/>
 *     <enumeration value="Flinn-Engdahl region"/>
 *     <enumeration value="local time"/>
 *     <enumeration value="tectonic summary"/>
 *     <enumeration value="nearest cities"/>
 *     <enumeration value="earthquake name"/>
 *     <enumeration value="region name"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "EventDescriptionType")
@XmlEnum
public enum EventDescriptionType {

    @XmlEnumValue("felt report")
    FELT_REPORT("felt report"),
    @XmlEnumValue("Flinn-Engdahl region")
    FLINN_ENGDAHL_REGION("Flinn-Engdahl region"),
    @XmlEnumValue("local time")
    LOCAL_TIME("local time"),
    @XmlEnumValue("tectonic summary")
    TECTONIC_SUMMARY("tectonic summary"),
    @XmlEnumValue("nearest cities")
    NEAREST_CITIES("nearest cities"),
    @XmlEnumValue("earthquake name")
    EARTHQUAKE_NAME("earthquake name"),
    @XmlEnumValue("region name")
    REGION_NAME("region name");
    private final String value;

    EventDescriptionType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static EventDescriptionType fromValue(String v) {
        for (EventDescriptionType c: EventDescriptionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
