//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.quakeml.xmlns.bed._1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for EventType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="EventType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="not existing"/>
 *     <enumeration value="not reported"/>
 *     <enumeration value="earthquake"/>
 *     <enumeration value="anthropogenic event"/>
 *     <enumeration value="collapse"/>
 *     <enumeration value="cavity collapse"/>
 *     <enumeration value="mine collapse"/>
 *     <enumeration value="building collapse"/>
 *     <enumeration value="explosion"/>
 *     <enumeration value="accidental explosion"/>
 *     <enumeration value="chemical explosion"/>
 *     <enumeration value="controlled explosion"/>
 *     <enumeration value="experimental explosion"/>
 *     <enumeration value="industrial explosion"/>
 *     <enumeration value="mining explosion"/>
 *     <enumeration value="quarry blast"/>
 *     <enumeration value="road cut"/>
 *     <enumeration value="blasting levee"/>
 *     <enumeration value="nuclear explosion"/>
 *     <enumeration value="induced or triggered event"/>
 *     <enumeration value="rock burst"/>
 *     <enumeration value="reservoir loading"/>
 *     <enumeration value="fluid injection"/>
 *     <enumeration value="fluid extraction"/>
 *     <enumeration value="crash"/>
 *     <enumeration value="plane crash"/>
 *     <enumeration value="train crash"/>
 *     <enumeration value="boat crash"/>
 *     <enumeration value="other event"/>
 *     <enumeration value="atmospheric event"/>
 *     <enumeration value="sonic boom"/>
 *     <enumeration value="sonic blast"/>
 *     <enumeration value="acoustic noise"/>
 *     <enumeration value="thunder"/>
 *     <enumeration value="avalanche"/>
 *     <enumeration value="snow avalanche"/>
 *     <enumeration value="debris avalanche"/>
 *     <enumeration value="hydroacoustic event"/>
 *     <enumeration value="ice quake"/>
 *     <enumeration value="slide"/>
 *     <enumeration value="landslide"/>
 *     <enumeration value="rockslide"/>
 *     <enumeration value="meteorite"/>
 *     <enumeration value="volcanic eruption"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "EventType")
@XmlEnum
public enum EventType {

    @XmlEnumValue("not existing")
    NOT_EXISTING("not existing"),
    @XmlEnumValue("not reported")
    NOT_REPORTED("not reported"),
    @XmlEnumValue("earthquake")
    EARTHQUAKE("earthquake"),
    @XmlEnumValue("anthropogenic event")
    ANTHROPOGENIC_EVENT("anthropogenic event"),
    @XmlEnumValue("collapse")
    COLLAPSE("collapse"),
    @XmlEnumValue("cavity collapse")
    CAVITY_COLLAPSE("cavity collapse"),
    @XmlEnumValue("mine collapse")
    MINE_COLLAPSE("mine collapse"),
    @XmlEnumValue("building collapse")
    BUILDING_COLLAPSE("building collapse"),
    @XmlEnumValue("explosion")
    EXPLOSION("explosion"),
    @XmlEnumValue("accidental explosion")
    ACCIDENTAL_EXPLOSION("accidental explosion"),
    @XmlEnumValue("chemical explosion")
    CHEMICAL_EXPLOSION("chemical explosion"),
    @XmlEnumValue("controlled explosion")
    CONTROLLED_EXPLOSION("controlled explosion"),
    @XmlEnumValue("experimental explosion")
    EXPERIMENTAL_EXPLOSION("experimental explosion"),
    @XmlEnumValue("industrial explosion")
    INDUSTRIAL_EXPLOSION("industrial explosion"),
    @XmlEnumValue("mining explosion")
    MINING_EXPLOSION("mining explosion"),
    @XmlEnumValue("quarry blast")
    QUARRY_BLAST("quarry blast"),
    @XmlEnumValue("road cut")
    ROAD_CUT("road cut"),
    @XmlEnumValue("blasting levee")
    BLASTING_LEVEE("blasting levee"),
    @XmlEnumValue("nuclear explosion")
    NUCLEAR_EXPLOSION("nuclear explosion"),
    @XmlEnumValue("induced or triggered event")
    INDUCED_OR_TRIGGERED_EVENT("induced or triggered event"),
    @XmlEnumValue("rock burst")
    ROCK_BURST("rock burst"),
    @XmlEnumValue("reservoir loading")
    RESERVOIR_LOADING("reservoir loading"),
    @XmlEnumValue("fluid injection")
    FLUID_INJECTION("fluid injection"),
    @XmlEnumValue("fluid extraction")
    FLUID_EXTRACTION("fluid extraction"),
    @XmlEnumValue("crash")
    CRASH("crash"),
    @XmlEnumValue("plane crash")
    PLANE_CRASH("plane crash"),
    @XmlEnumValue("train crash")
    TRAIN_CRASH("train crash"),
    @XmlEnumValue("boat crash")
    BOAT_CRASH("boat crash"),
    @XmlEnumValue("other event")
    OTHER_EVENT("other event"),
    @XmlEnumValue("atmospheric event")
    ATMOSPHERIC_EVENT("atmospheric event"),
    @XmlEnumValue("sonic boom")
    SONIC_BOOM("sonic boom"),
    @XmlEnumValue("sonic blast")
    SONIC_BLAST("sonic blast"),
    @XmlEnumValue("acoustic noise")
    ACOUSTIC_NOISE("acoustic noise"),
    @XmlEnumValue("thunder")
    THUNDER("thunder"),
    @XmlEnumValue("avalanche")
    AVALANCHE("avalanche"),
    @XmlEnumValue("snow avalanche")
    SNOW_AVALANCHE("snow avalanche"),
    @XmlEnumValue("debris avalanche")
    DEBRIS_AVALANCHE("debris avalanche"),
    @XmlEnumValue("hydroacoustic event")
    HYDROACOUSTIC_EVENT("hydroacoustic event"),
    @XmlEnumValue("ice quake")
    ICE_QUAKE("ice quake"),
    @XmlEnumValue("slide")
    SLIDE("slide"),
    @XmlEnumValue("landslide")
    LANDSLIDE("landslide"),
    @XmlEnumValue("rockslide")
    ROCKSLIDE("rockslide"),
    @XmlEnumValue("meteorite")
    METEORITE("meteorite"),
    @XmlEnumValue("volcanic eruption")
    VOLCANIC_ERUPTION("volcanic eruption");
    private final String value;

    EventType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static EventType fromValue(String v) {
        for (EventType c: EventType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
