//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.quakeml.xmlns.bed._1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for OriginType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="OriginType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="hypocenter"/>
 *     <enumeration value="centroid"/>
 *     <enumeration value="amplitude"/>
 *     <enumeration value="macroseismic"/>
 *     <enumeration value="rupture start"/>
 *     <enumeration value="rupture end"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "OriginType")
@XmlEnum
public enum OriginType {

    @XmlEnumValue("hypocenter")
    HYPOCENTER("hypocenter"),
    @XmlEnumValue("centroid")
    CENTROID("centroid"),
    @XmlEnumValue("amplitude")
    AMPLITUDE("amplitude"),
    @XmlEnumValue("macroseismic")
    MACROSEISMIC("macroseismic"),
    @XmlEnumValue("rupture start")
    RUPTURE_START("rupture start"),
    @XmlEnumValue("rupture end")
    RUPTURE_END("rupture end");
    private final String value;

    OriginType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static OriginType fromValue(String v) {
        for (OriginType c: OriginType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
