//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.quakeml.xmlns.bed._1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for OriginDepthType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="OriginDepthType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="from location"/>
 *     <enumeration value="from moment tensor inversion"/>
 *     <enumeration value="from modeling of broad-band P waveforms"/>
 *     <enumeration value="constrained by depth phases"/>
 *     <enumeration value="constrained by direct phases"/>
 *     <enumeration value="constrained by depth and direct phases"/>
 *     <enumeration value="operator assigned"/>
 *     <enumeration value="other"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "OriginDepthType")
@XmlEnum
public enum OriginDepthType {

    @XmlEnumValue("from location")
    FROM_LOCATION("from location"),
    @XmlEnumValue("from moment tensor inversion")
    FROM_MOMENT_TENSOR_INVERSION("from moment tensor inversion"),
    @XmlEnumValue("from modeling of broad-band P waveforms")
    FROM_MODELING_OF_BROAD_BAND_P_WAVEFORMS("from modeling of broad-band P waveforms"),
    @XmlEnumValue("constrained by depth phases")
    CONSTRAINED_BY_DEPTH_PHASES("constrained by depth phases"),
    @XmlEnumValue("constrained by direct phases")
    CONSTRAINED_BY_DIRECT_PHASES("constrained by direct phases"),
    @XmlEnumValue("constrained by depth and direct phases")
    CONSTRAINED_BY_DEPTH_AND_DIRECT_PHASES("constrained by depth and direct phases"),
    @XmlEnumValue("operator assigned")
    OPERATOR_ASSIGNED("operator assigned"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    OriginDepthType(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static OriginDepthType fromValue(String v) {
        for (OriginDepthType c: OriginDepthType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
