//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.quakeml.xmlns.bed._1;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for OriginUncertaintyDescription</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="OriginUncertaintyDescription">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="horizontal uncertainty"/>
 *     <enumeration value="uncertainty ellipse"/>
 *     <enumeration value="confidence ellipsoid"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "OriginUncertaintyDescription")
@XmlEnum
public enum OriginUncertaintyDescription {

    @XmlEnumValue("horizontal uncertainty")
    HORIZONTAL_UNCERTAINTY("horizontal uncertainty"),
    @XmlEnumValue("uncertainty ellipse")
    UNCERTAINTY_ELLIPSE("uncertainty ellipse"),
    @XmlEnumValue("confidence ellipsoid")
    CONFIDENCE_ELLIPSOID("confidence ellipsoid");
    private final String value;

    OriginUncertaintyDescription(String v) {
        value = v;
    }

    /**
     * Gets the value associated to the enum constant.
     * 
     * @return
     *     The value linked to the enum.
     */
    public String value() {
        return value;
    }

    /**
     * Gets the enum associated to the value passed as parameter.
     * 
     * @param v
     *     The value to get the enum from.
     * @return
     *     The enum which corresponds to the value, if it exists.
     * @throws IllegalArgumentException
     *     If no value matches in the enum declaration.
     */
    public static OriginUncertaintyDescription fromValue(String v) {
        for (OriginUncertaintyDescription c: OriginUncertaintyDescription.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
