name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18-ea' ]
        os: [ 'windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_OPTS: -Dhttp.keepAlive=false
    steps:
    - uses: actions/checkout@v2
    - if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo dpkg --add-architecture i386
        wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
        sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
        sudo apt-get update
        sudo apt-get install -y --install-recommends wine-stable winehq-stable
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - run: mvn clean verify -B -V -e -ntp
    - if: matrix.os == 'ubuntu-latest' && matrix.java == '17'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: git fetch --unshallow && mvn package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=albertus82-github -B -V -e -ntp
